const prodcatelas = document.querySelector('.catalogoelas')

class Deportiva extends Producto{
    constructor(props){
        super(props)
    }
}



const elas1 = new Deportiva({
    modelo: "Greta",
    talla:"L | M | S",
    tela:"Lycra | Algodón",
    color:"Negro | Turqueza",
    descripcion:"Un atuendo más relajado. Ideal para ensayos cotidianos. Viene acompañad de pareo de danza",
    imagen:"./media/prendas/elastano/e.png",
    imagen2:"./media/prendas/elastano/e1.png",
    imagen3:"./media/prendas/elastano/e2.png",
    imagen4:"./media/prendas/elastano/e3.png",
    esDeportiva: "true",
})
const elas2 = new Deportiva({
    modelo: "Greta",
    talla:"L | M | S",
    tela:"Lycra | Algodón",
    color:"Negro | Turqueza",
    descripcion:"El mejor de los atuendos para la mejor de las bailarinas",
    imagen:"./media/prendas/elastano/e4.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas3 = new Deportiva({
    modelo: "Greta",
    talla:"L | M | S",
    tela:"Lycra | Algodón",
    color:"Negro | Turqueza",
    descripcion:"Un atuendo más relajado. Ideal para ensayos cotidianos. Viene acompañad de pareo de danza",
    imagen:"./media/prendas/elastano/e5.jpg",
    imagen2:"",
    esDeportiva: "true",
})
const elas4 = new Deportiva({
    modelo: "Greta",
    talla:"L | M | S",
    tela:"Lycra | Algodón",
    color:"Negro | Turqueza",
    descripcion:"Un atuendo más relajado. Ideal para ensayos cotidianos. Viene acompañad de pareo de danza",
    imagen:"./media/prendas/elastano/e6.jpg",
    imagen2:"",
    esDeportiva: "true",
})
const elas5 = new Deportiva({
    modelo: "Dasia",
    talla:"L | M | S",
    tela:"Lycra | Algodón",
    color:"Negro | Turqueza",
    descripcion:"Un look súper relajado. Ideal para encontrar comodidad en los fines de semana o dentro del hogar",
    imagen:"./media/prendas/elastano/e7.jpg",
    imagen2:"./media/prendas/elastano/e8.jpg",
    esDeportiva: "true",
})
const elas6 = new Deportiva({
    modelo: "Mariana",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Negro | Turqueza",
    descripcion:"Enterizo ideal para salidas más aventureras, permite visualización de la línea de cuerpo y es más adecuado para actividades de alto riesgo que requieren presencia y elegancia.",
    imagen:"/media/prendas/elastano/e9.png",
    imagen2:"./media/prendas/elastano/e10.png",
    esDeportiva: "true",
})
const elas7 = new Deportiva({
    modelo: "Greta",
    talla:"L | M | S",
    tela:"Lycra | Algodón",
    color:"Negro | Turqueza",
    descripcion:"Un atuendo más relajado. Ideal para ensayos cotidianos. Viene acompañad de pareo de danza",
    imagen:"./media/prendas/elastano/e11.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas8 = new Deportiva({
    modelo: "Greta",
    talla:"L | M | S",
    tela:"Lycra | Algodón",
    color:"Negro | Turqueza",
    descripcion:"Un atuendo más relajado. Ideal para ensayos cotidianos. Viene acompañad de pareo de danza",
    imagen:"./media/prendas/elastano/e12.png",
    imagen2:"./media/prendas/elastano/e13.png",
    imagen3:"./media/prendas/elastano/e14.png",
    esDeportiva: "true",
})
const elas9 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e15.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas10 = new Deportiva({
    modelo: "Este",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e16.png",
    imagen2:"./media/prendas/elastano/e17.png",
    imagen3:"./media/prendas/elastano/e18.png",
    esDeportiva: "true",
})
const elas11 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e10.png",
    imagen2:"",
    imagen3:"",
    esDeportiva: "true",
})
const elas12 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e11.png",
    imagen2:"",
    imagen3:"",
    imagen2:"",
    esDeportiva: "true",
})
const elas13 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e12.png",
    imagen2:"./media/prendas/elastano/e13.png",
    imagen3:"./media/prendas/elastano/e14.png",
    esDeportiva: "true",
})
const elas14 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e15.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas15 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e16.png",
    imagen2:"./media/prendas/elastano/e17.png",
    imagen3:"./media/prendas/elastano/e18.png",
    esDeportiva: "true",
})
const elas16 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e19.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas17 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e20.png",
    imagen2:"",
    imagen3:"",
    esDeportiva: "true",
})
const elas18 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e21.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas19 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e22.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas20 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e23.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas21 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e24.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas22 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e25.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas23 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e26.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas24 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e27.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas25 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e28.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas26 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e29.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas27 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e30.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas28 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e31.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas29 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e32.png",
    imagen2:"./media/prendas/elastano/e33.png",
    esDeportiva: "true",
})
const elas30 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e34.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas31 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e35.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas32 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e36.png",
    imagen2:"./media/prendas/elastano/e37.png",
    esDeportiva: "true",
})
const elas33 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e38.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas34 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e39.png",
    imagen2:"./media/prendas/elastano/e40.png",
    imagen3:"./media/prendas/elastano/e41.png",
    imagen4:"./media/prendas/elastano/e42.png",
    esDeportiva: "true",
})
const elas35 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e43.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas36 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e44.png",
    imagen2:"./media/prendas/elastano/e45.png",
    esDeportiva: "true",
})
const elas37 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e46.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas38 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e47.png",
    imagen2:"./media/prendas/elastano/e48.png",
    imagen3:"./media/prendas/elastano/e49.png",
    imagen4:"./media/prendas/elastano/e50.png",
    esDeportiva: "true",
    



})
const elas39 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e51.png",
    imagen2:"",
    esDeportiva: "true",
})
const elas40 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e52.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    esDeportiva: "true",
})

const elas41 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e53.png",
    imagen2:"./media/prendas/elastano/e54.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas42 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e55.png",
    imagen2:"./media/prendas/elastano/e56.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas43 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e57.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas44 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e58.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas45 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e59.png",
    imagen2:"./media/prendas/elastano/e60.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas46 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e61.png",
    imagen2:"./media/prendas/elastano/e62.png",
    imagen3:"./media/prendas/elastano/e63.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas47 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e64.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas48 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e65.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas49 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e66.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas50 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e67.png",
    imagen2:"./media/prendas/elastano/e74.png",
    imagen3:"./media/prendas/elastano/e75.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas51 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e68.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas52 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e69.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas53 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e70.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas54 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e71.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas55 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e72.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas56 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e73.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas57 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e76.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas58 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e77.png",
    imagen2:"./media/prendas/elastano/e78.png",
    imagen3:"./media/prendas/elastano/e79.png",
    imagen4:"./media/prendas/elastano/e80.png",
    imagen5:"./media/prendas/elastano/e81.png",
    esDeportiva: "true",
})
const elas59 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e83.png",
    imagen2:"./media/prendas/elastano/e82.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas60 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e84.png",
    imagen2:"./media/prendas/elastano/e85.png",
    imagen3:"./media/prendas/elastano/e86.png",
    imagen4:"./media/prendas/elastano/e87.png",
    imagen5:"",
    esDeportiva: "true",
})
const elas61 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e88.png",
    imagen2:"./media/prendas/elastano/e89.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas62 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e90.png",
    imagen2:"./media/prendas/elastano/e91.png",
    imagen3:"./media/prendas/elastano/e92.png",
    imagen4:"./media/prendas/elastano/e93.png",
    imagen5:"./media/prendas/elastano/e94.png",
    esDeportiva: "true",
})
const elas63 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e96.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas64 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e97.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas65 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e98.png",
    imagen2:"./media/prendas/elastano/e99.png",
    imagen3:"./media/prendas/elastano/e100.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas66 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e101.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas67 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e102.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas68 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e103.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas69 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e104.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas70 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e105.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas71 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e106.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas72 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e107.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas73 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e108.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas74 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e109.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas75 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e110.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas76 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e111.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas77 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e112.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas78 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e113.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas79 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e114.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas80 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e115.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas81 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e116.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas82 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e117.png",
    imagen2:"./media/prendas/elastano/e118.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas83 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e119.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas84 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e120.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas85 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e121.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas86 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e122.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas87 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e123.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas88 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e124.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas89 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e125.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas90 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e126.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas91 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e127.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas92 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e128.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas93 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e129.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas94 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e130.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas95 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e131.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas96 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e132.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas97 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e133.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas98 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e134.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas99 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e135.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas100 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e136.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas101 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e137.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas102 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e138.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas103 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e139.png",
    imagen2:"./media/prendas/elastano/e140.png",
    imagen3:"./media/prendas/elastano/e141.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas104 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e142.png",
    imagen2:"./media/prendas/elastano/e143.png",
    imagen3:"./media/prendas/elastano/e144.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas105 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e145.png",
    imagen2:"./media/prendas/elastano/e146.png",
    imagen3:"./media/prendas/elastano/e147.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas106 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e148.png",
    imagen2:"./media/prendas/elastano/e149.png",
    imagen3:"./media/prendas/elastano/e150.png",
    imagen4:"./media/prendas/elastano/e151.png",
    imagen5:"./media/prendas/elastano/e152.png",
    esDeportiva: "true",
})
const elas107 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e173.png",
    imagen2:"./media/prendas/elastano/e174.png",
    imagen3:"./media/prendas/elastano/e175.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas108 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e153.png",
    imagen2:"./media/prendas/elastano/e154.png",
    imagen3:"./media/prendas/elastano/e155.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas109 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e156.png",
    imagen2:"./media/prendas/elastano/e157.png",
    imagen3:"./media/prendas/elastano/e158.png",
    imagen4:"./media/prendas/elastano/e161.png",
    imagen5:"./media/prendas/elastano/e162.png",
    esDeportiva: "true",
})
const elas110 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e165.png",
    imagen2:"./media/prendas/elastano/e166.png",
    imagen3:"./media/prendas/elastano/e167.png",
    imagen4:"./media/prendas/elastano/e168.png",
    imagen5:"./media/prendas/elastano/e169.png",
    esDeportiva: "true",
})
const elas111 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e170.png",
    imagen2:"./media/prendas/elastano/e171.png",
    imagen3:"./media/prendas/elastano/e172.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas112 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e176.png",
    imagen2:"./media/prendas/elastano/e177.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas113 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e178.png",
    imagen2:"./media/prendas/elastano/e179.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas114 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e180.png",
    imagen2:"./media/prendas/elastano/e181.png",
    imagen3:"./media/prendas/elastano/e182.png",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas115 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e183.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas116 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e184.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas117 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e185.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas118 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e186.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas119 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e187.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas120 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e188.png",
    imagen2:"./media/prendas/elastano/e189.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas121 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e190.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas122 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e191.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas123 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e192.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas124 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e193.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas125 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e194.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas126 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e195.png",
    imagen2:"./media/prendas/elastano/e196.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas127 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e197.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas128 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e198.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas129 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e199.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas130 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e200.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas131 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e201.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas132 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e202.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas133 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e203.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})
const elas134 = new Deportiva({
    modelo: "",
    talla:"L | M | S",
    tela:"Elastano",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/elastano/e204.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDeportiva: "true",
})



var productos = [
    elas1,
    elas2,
    elas3,
    elas4,
    elas5,
    elas6,
    elas7,
    elas8,
    elas9,
    elas10,
    elas11,
    elas12,
    elas13,
    elas14,
    elas15,
    elas16,
    elas17,
    elas18,
    elas19,
    elas20,
    elas21,
    elas22,
    elas23,
    elas24,
    elas25,
    elas26,
    elas27,
    elas28,
    elas29,
    elas30,
    elas31,
    elas32,
    elas33,
    elas34,
    elas35,
    elas36,
    elas37,
    elas38,
    elas39,
    elas40,
    elas41,
    elas42,
    elas43,
    elas44,
    elas45,
    elas46,
    elas47,
    elas48,
    elas49,
    elas50,
    elas51,
    elas52,
    elas53,
    elas54,
    elas55,
    elas56,
    elas57,
    elas58,
    elas59,
    elas60,
    elas61,
    elas62,
    elas63,
    elas64,
    elas65,
    elas66,
    elas67,
    elas68,
    elas69,
    elas70,
    elas71,
    elas72,
    elas73,
    elas74,
    elas75,
    elas76,
    elas77,
    elas78,
    elas79,
    elas80,
    elas81,
    elas82,
    elas83,
    elas84,
    elas85,
    elas86,
    elas87,
    elas88,
    elas89,
    elas90,
    elas91,
    elas92,
    elas93,
    elas94,
    elas95,
    elas96,
    elas97,
    elas98,
    elas99,


    elas101,
    elas102,
    elas103,
    elas104,
    elas105,
    elas106,
    elas107,
    elas108,
    elas109,
    elas110,
    elas111,
    elas112,
    elas113,
    elas114,
    elas115,
    elas116,
    elas110,
    elas117,
    elas118,
    elas119,
    elas120,
    elas121,
    elas122,
    elas123,
    elas124,
    elas125,
    elas126,
    elas127,
    elas128,
    elas129,
    elas130,
    elas131,
    elas132,
    elas133,
    elas134,
    //elas135,
    //elas136,
    //elas137,
    //elas138,
    //elas139,
    //elas140,
    //elas141,
    //elas142,
    //elas143,
    //elas144,
    //elas145,
    //elas146,
    //elas147,
    //elas148,
    //elas149,
    //elas150,
    //elas151,
    //elas152,
    //elas153,
    //elas154,
    //elas155,
    //elas156,
    //elas157,
    //elas158,
    //elas159,
    //elas160,
    //elas161,
    //elas162,
    //elas163,
    //elas164,
    //elas165,
    //elas166,
    //elas167,
    //elas168,
    //elas169,
    //elas170,
    //elas171,
    //elas172,
    //elas173,
    //elas174,
    //elas175,
    //elas176,
    //elas177,
    //elas178,
    //elas179,
    //elas180,
    //elas181,
    //elas182,
    //elas183,
    //elas184,
    //elas185,
    //elas186,
    //elas187,
    //elas188,
    //elas189,
    //elas190,
    //elas191,
    //elas192,
    //elas193,
    //elas194,
    //elas195,
    //elas196,
    //elas197,
    //elas198,
    //elas199
]


productos.forEach(function(producto) {
    var productoElement = document.createElement("div");
    productoElement.classList.add("busqueda")
    productoElement.innerHTML = `
      <h4>${producto.modelo}</h4>
      <div class="caja">
        <div class="galeria">
          ${producto.imagen ? `<img src="${producto.imagen}" alt="">` : ''}
          ${producto.imagen2 ? `<img src="${producto.imagen2}" alt="">` : ''}
          ${producto.imagen3 ? `<img src="${producto.imagen3}" alt="">` : ''}
          ${producto.imagen4 ? `<img src="${producto.imagen4}" alt="">` : ''}
        </div>
      </div>
      <div class="contenedorVistaPrevia">
        ${producto.imagen ? `<img src="${producto.imagen}" alt="">` : ''}
        ${producto.imagen2 ? `<img src="${producto.imagen2}" alt="">` : ''}
        ${producto.imagen3 ? `<img src="${producto.imagen3}" alt="">` : ''}
        ${producto.imagen4 ? `<img src="${producto.imagen4}" alt="">` : ''}
      </div>
      <div class="parrafos">
        <p>Tallas disponibles: ${producto.talla}</p>
        <p>Tela: ${producto.tela}</p>
        <p>${producto.descripcion}</p>
      </div>`;
  
    // Calcula el ancho del contenedor .galeria en función de la cantidad de imágenes
    var numImagenes = 0;
    if (producto.imagen) numImagenes++;
    if (producto.imagen2) numImagenes++;
    if (producto.imagen3) numImagenes++;
    if (producto.imagen4) numImagenes++;
  
    // Aplica el ancho calculado al contenedor .galeria
    var galeriaElement = productoElement.querySelector(".galeria");
    galeriaElement.style.width = numImagenes * 100 + "%";
  
    prodcatelas.appendChild(productoElement);
  });