const prodcatal = document.querySelector('.lenceria')

class Lenceria extends Producto{
    constructor(props){
        super(props)
    }
    tipoprenda(estiloprenda){
        if(estiloprenda.esLenceria){
            this.tipo.push(estiloprenda)
        }
    }
}

const lence1 = new Lenceria({
    modelo:"Alguno",
    esLenceria:true,
    imagen:"https://pbs.twimg.com/media/EIUk1YzX0AA25qE.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:false,
    esLenceria:true,
})
const lence2 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aaaa.png",
    imagen2:"./media/prendas/lenceria/conjuntos/aaaa1.png",
    imagen3:"./media/prendas/lenceria/conjuntos/aaaa2.png",
    imagen4:"./media/prendas/lenceria/conjuntos/aaaa3.png",
    esDanza:false,
    esLenceria:true,
})
const lence3 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aade1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence4 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aald.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence5 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx1.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence6 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx2.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence7 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx3.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence8 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx4.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence9 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx5.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence10 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx6.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence11 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx7.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence12 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx8.jpg",
    esDanza:false,
    esLenceria:true,
})
const lence13 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx9.jpg",
    imagen5:"",
    esDanza:false,
    esLenceria:true,
})
const lence14 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx10.jpg",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence15 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aalx11.jpg",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence16 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aana.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence17 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aanc.png",
    imagen2:"./media/prendas/lenceria/conjuntos/aanc1.png",
    imagen3:"./media/prendas/lenceria/conjuntos/aanc2.png",
    imagen4:"./media/prendas/lenceria/conjuntos/aanc3.png",
    esDanza:false,
    esLenceria:true,
})
const lence18 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aash.png",
    imagen2:"./media/prendas/lenceria/conjuntos/aash1.png",
    imagen3:"./media/prendas/lenceria/conjuntos/aash2.png",
    imagen4:"./media/prendas/lenceria/conjuntos/aash3.png",
    esDanza:false,
    esLenceria:true,
})
const lence19 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aash4.png",
    imagen2:"./media/prendas/lenceria/conjuntos/aash5.png",
    imagen3:"./media/prendas/lenceria/conjuntos/aash6.png",
    esDanza:false,
    esLenceria:true,
})
const lence20 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/belva1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/belva2.png",
    esDanza:false,
    esLenceria:true,
})
const lence21 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/bun1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/bun2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/bun3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/bun4.png",
    imagen5:"./media/prendas/lenceria/conjuntos/bun5.png",
    esDanza:false,
    esLenceria:true,
})
const lence22 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/aylra1.jpg",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence23 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/bodna1.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:false,
    esLenceria:true,
})
const lence24 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/bodnb1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence25 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/brana1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence26 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/brwca1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence27 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/camba1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence28 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/camna1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence29 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/catba1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/catba2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/catba3.png",
    esDanza:false,
    esLenceria:true,
})
const lence30 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/catra1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/catra2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/catra3.png",
    esDanza:false,
    esLenceria:true,
})
const lence31 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/cecra1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence32 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/chena1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence33 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/chera1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence34 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/colna1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence35 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/colnb1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence36 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/corna1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/corna2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/corna3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/corna4.png",
    imagen5:"./media/prendas/lenceria/conjuntos/corna5.png",
    imagen6:"./media/prendas/lenceria/conjuntos/corna6.png",
    esDanza:false,
    esLenceria:true,
})
const lence37 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/danb1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/danna1.png",
    imagen3:"",
    imagen4:"",
    esDanza:false,
    esLenceria:true,
})
const lence38 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/decba1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence39 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/ferpa1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/ferpa2.png",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence40 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/getla1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence41 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/gigga1.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    imagen6:"",
    esDanza:false,
    esLenceria:true,
})
const lence42 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/grenb1.jpg",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence43 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/greba1.jpg",
    imagen2:"./media/prendas/lenceria/conjuntos/greba2.jpg",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence44 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/grebb1.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:false,
    esLenceria:true,
})
const lence45 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/grefa1.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence46 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/grena1.jpg",
    imagen2:"./media/prendas/lenceria/conjuntos/grena2.jpg",
    imagen3:"",
    imagen4:"",
    esDanza:false,
    esLenceria:true,
})
const lence47 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/grepa1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence48 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/greva1.jpg",
    imagen2:"./media/prendas/lenceria/conjuntos/greva2.jpg",
    imagen3:"",
    imagen4:"",
    esDanza:false,
    esLenceria:true,
})
const lence49 = new Lenceria({
    modelo: "Greta Verde",
    talla:"L | M | S",
    tela:"lycra",
    color:"verde",
    descripcion:"El modelo de mayor petición para conciertos.",
    imagen:"./media/prendas/lenceria/conjuntos/grevb1.jpg",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence50 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/guana1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/guana2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/guana3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/guana4.png",
    esDanza:false,
    esLenceria:true,
})
const lence51 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/jacra1.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    imagen6:"",
    esDanza:false,
    esLenceria:true,
})
const lence52 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/jckna1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/jckna2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/jckna3.png",
    esDanza:false,
    esLenceria:true,
})
const lence53 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/jesna1.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    esDanza:false,
    esLenceria:true,
})
const lence54 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/jnf1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence55 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/jnf2.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    esDanza:false,
    esLenceria:true,
})
const lence56 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julaa1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julaa2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julaa3.png",
    esDanza:false,
    esLenceria:true,
})
const lence57 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julba1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julba2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julba3.png",
    imagen4:"",
    imagen5:"",
    imagen6:"",
    esDanza:false,
    esLenceria:true,
})
const lence58 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julbb1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence59 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julbc1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence60 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julbd1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence61 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julbe1.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    esDanza:false,
    esLenceria:true,
})
const lence62 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julbf1.png",
    imagen3:"",
    imagen2:"",
    imagen4:"",
    esDanza:false,
    esLenceria:true,
})
const lence63 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julbg1.png",
    imagen3:"",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence64 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julga1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence65 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julgb1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence66 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julla1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julla2.png",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence67 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julma1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julma2.png",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence68 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julna1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julna2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julna3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/julna4.png",
    imagen5:"./media/prendas/lenceria/conjuntos/julna5.png",
    esDanza:false,
    esLenceria:true,
})
const lence69 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnb1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julnb2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julnb3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/julnb4.png",
    esDanza:false,
    esLenceria:true,
})
const lence70 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnc1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julnc2.png",
    esDanza:false,
    esLenceria:true,
})
const lence71 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnd1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julnd2.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:false,
    esLenceria:true,
})
const lence72 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julne1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julne2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julne3.png",
    esDanza:false,
    esLenceria:true,
})
const lence73 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnf1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julnf2.png",
    esDanza:false,
    esLenceria:true,
})
const lence74 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnh1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence75 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julni1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julni2.png",
    esDanza:false,
    esLenceria:true,
})
const lence76 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnj1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence77 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnk1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence78 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnm1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julnm2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julnm3.png",
    esDanza:false,
    esLenceria:true,
})
const lence79 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnn1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julnn2.png",
    esDanza:false,
    esLenceria:true,
})
const lence80 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julno1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julno2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julno3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/julno4.png",
    imagen5:"./media/prendas/lenceria/conjuntos/julno5.png",
    esDanza:false,
    esLenceria:true,
})
const lence81 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julnp1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julnp2.png",
    esDanza:false,
    esLenceria:true,
})
const lence82 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julpa1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence83 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julpb1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence84 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julpc1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence85 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julra1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/julra2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/julra3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/julra4.png",
    esDanza:false,
    esLenceria:true,
})
const lence86 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julrb1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence87 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julrc1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence88 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julrd1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence89 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julre1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence90 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/julta1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence91 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/kitba1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence92 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/kitm1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/kitm2.png",
    esDanza:false,
    esLenceria:true,
})
const lence93 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/kitn1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/kitn2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/kitn3.png",
    esDanza:false,
    esLenceria:true,
})
const lence94 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/kocn1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence95 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/laifa1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/laifa2.png",
    esDanza:false,
    esLenceria:true,
})

const lence96 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/laima1.png",
    imagen2:"",
    esDanza:false,
    esLenceria:true,
})
const lence97 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/laina1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/laina2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/laina3.png",
    imagen4:"./media/prendas/lenceria/conjuntos/laina4.png",
    esDanza:false,
    esLenceria:true,
})
const lence98 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/lainb1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/lainb2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/lainb3.png",
    esDanza:false,
    esLenceria:true,
})
const lence99 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/lainc1.png",
    imagen2:"./media/prendas/lenceria/conjuntos/lainc2.png",
    imagen3:"./media/prendas/lenceria/conjuntos/lainc3.png",
    esDanza:false,
    esLenceria:true,
})
const lence100 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/laind1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence101 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/laine1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence102 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/lainf1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence103 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/laing1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})
const lence104 = new Lenceria({
    modelo: "",
    talla:"L | M | S",
    tela:"",
    color:"",
    descripcion:"",
    imagen:"./media/prendas/lenceria/conjuntos/lainh1.png",
    imagen2:"",
    imagen3:"",
    esDanza:false,
    esLenceria:true,
})

var productos = [
    lence1,
    lence2,
    lence3,
    lence4,
    lence5,
    lence6,
    lence7,
    lence8,
    lence9,
    lence10,
    lence11,
    lence12,
    lence13,
    lence14,
    lence15,
    lence16,
    lence17,
    lence18,
    lence19,
    lence20,
    lence21,
    lence22,
    lence23,
    lence24,
    lence25,
    lence26,
    lence27,
    lence28,
    lence29,
    lence30,
    lence31,
    lence32,
    lence33,
    lence34,
    lence35,
    lence36,
    lence37,
    lence38,
    lence39,
    lence40,
    lence41,
    lence42,
    lence43,
    lence44,
    lence45,
    lence46,
    lence47,
    lence48,
    lence49,
    lence50,
    lence51,
    lence52,
    lence53,
    lence54,
    lence55,
    lence56,
    lence57,
    lence58,
    lence59,
    lence60,
    lence61,
    lence62,
    lence63,
    lence64,
    lence65,
    lence66,
    lence67,
    lence68,
    lence69,
    lence70,
    lence71,
    lence72,
    lence73,
    lence74,
    lence75,
    lence76,
    lence77,
    lence78,
    lence79,
    lence80,
    lence81,
    lence82,
    lence83,
    lence84,
    lence85,
    lence86,
    lence87,
    lence88,
    lence89,
    lence90,
    lence91,
    lence92,
    lence93,
    lence94,
    lence95,
    /*lence96,
    lence97,
    lence98,
    lence99,
    lence100,
    lence101,
    lence102,
    lence103,
    lence104,
    lence105,
    lence106,
    lence107,
    lence108,
    lence109,*/
]


productos.forEach(function(producto)
{
    var productoElement = document.createElement("div")

    productoElement.innerHTML = `<h4>
    ${producto.modelo}</h4><div class="galeria"><img src="
    ${producto.imagen}" alt=""><img src="
    ${producto.imagen2}" alt=""><img src="
    ${producto.imagen3}" alt=""><img src="
    ${producto.imagen4}" alt=""></div><div class="contenedorVistaPrevia"><img src="
    ${producto.imagen2}" alt=""><img src="
    ${producto.imagen3}" alt=""><img src="
    ${producto.imagen4}" alt=""></div><div class: "parrafos"> <p>Tallas disponibles: 
    ${producto.talla}</p><p>Tela: 
    ${producto.tela}</p><p>
    ${producto.descripcion}</p></div>`

    prodcatal.appendChild(productoElement)
})