const prodcatatb = document.querySelector('.trajesdebaño')


class TrajesBano extends Producto{
    constructor(props){
        super(props)
    }
    tipoprenda(estiloprenda){
        if(estiloprenda.esTrajeB){
            this.tipo.push(estiloprenda)
        }
    }
}
const tb1 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rojo",
    descripcion:"Traje de baño ideal para lucir en albercas y playas. Definitivamente su trazo hace que el cuerpo tenga una mejor segmentación.",
    imagen:"./media/prendas/trajesBaño/tb1.png",
    imagen2:"./media/prendas/trajesBaño/tb2.png",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb2 = new TrajesBano({
    modelo: "Ana VEnko Blue",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Azul",
    descripcion:"Maneja un tono de lycra que combina perfecto para los atadecerres en la playa",
    imagen:"./media/prendas/trajesBaño/tb3.png",
    imagen2:"./media/prendas/trajesBaño/tb4.png",
    imagen3:"./media/prendas/trajesBaño/tb5.png",
    imagen4:"./media/prendas/trajesBaño/tb8.png",
    imagen5:"./media/prendas/trajesBaño/tb7.png",
    esDanza:"",
    estbria:"",
})
const tb3 = new TrajesBano({
    modelo: "Beth",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb9.png",
    imagen2:"./media/prendas/trajesBaño/tb10.png",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb4 = new TrajesBano({
    modelo: "Aziel amar",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb11.png",
    imagen2:"./media/prendas/trajesBaño/tb12.png",
    imagen3:"./media/prendas/trajesBaño/tb13.png",
    imagen4:"./media/prendas/trajesBaño/tb14.png",
    imagen5:"./media/prendas/trajesBaño/tb15.png",
    esDanza:"",
    estbria:"",
})
const tb5 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb18.png",
    imagen2:"./media/prendas/trajesBaño/tb20.png",
    imagen3:"",
    imagen4:"",
    esDanza:"",
    estbria:"",
})
const tb6 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb19.png",
    imagen2:"",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb7 = new TrajesBano({
    modelo: "Alessa",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb21.png",
    imagen2:"",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb8 = new TrajesBano({
    modelo: "Andy Cano",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb22.jpg",
    imagen2:"",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb9 = new TrajesBano({
    modelo: "Andy black",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb23.png",
    imagen2:"",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb10 = new TrajesBano({
    modelo: "Ardilla",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb24.png",
    imagen2:"",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb11 = new TrajesBano({
    modelo: "Azul",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb25.png",
    imagen2:"",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb12 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb26.png",
    imagen2:"./media/prendas/trajesBaño/tb27.png",
    imagen3:"./media/prendas/trajesBaño/tb28.png",
    imagen4:"./media/prendas/trajesBaño/tb29.png",
    imagen5:"./media/prendas/trajesBaño/tb31.png",
    esDanza:"",
    estbria:"",
})
const tb13 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb33.png",
    imagen2:"",
    imagen3:"",
    esDanza:"",
    estbria:"",
})
const tb14 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb34.png",
    imagen2:"./media/prendas/trajesBaño/tb35.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb15 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb36.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb16 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb37.png",
    imagen2:"./media/prendas/trajesBaño/tb38.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb17 = new TrajesBano({
    modelo: "Laila Bl",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb39.png",
    imagen2:"./media/prendas/trajesBaño/tb40.png",
    imagen3:"./media/prendas/trajesBaño/tb41.png",
    imagen4:"./media/prendas/trajesBaño/tb42.png",
    imagen5:"./media/prendas/trajesBaño/tb43.png",
    esDanza:"",
    estbria:"",
})
const tb18 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb44.png",
    imagen2:"./media/prendas/trajesBaño/tb45.png",
    imagen3:"./media/prendas/trajesBaño/tb46.png",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb19 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb47.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb20 = new TrajesBano({
    modelo: "Liz",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb48.png",
    imagen2:"./media/prendas/trajesBaño/tb49.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb21 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb50.png",
    imagen2:"./media/prendas/trajesBaño/tb51.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb22 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb52.png",
    imagen2:"./media/prendas/trajesBaño/tb53.png",
    imagen3:"./media/prendas/trajesBaño/tb54.png",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb23 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb55.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb24 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb56.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb25 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb57.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb26 = new TrajesBano({
    modelo: "Anna",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb58.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb27 = new TrajesBano({
    modelo: "Liz mesh",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb59.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb28 = new TrajesBano({
    modelo: "Luma",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb60.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb29 = new TrajesBano({
    modelo: "Merari",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb62.png",
    imagen2:"./media/prendas/trajesBaño/tb63.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb30 = new TrajesBano({
    modelo: "Mar",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb64.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb31 = new TrajesBano({
    modelo: "Mar",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb65.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb32 = new TrajesBano({
    modelo: "Monica",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb66.png",
    imagen2:"./media/prendas/trajesBaño/tb67.png",
    imagen3:"./media/prendas/trajesBaño/tb68.png",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb33 = new TrajesBano({
    modelo: "Mon brown",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb69.png",
    imagen2:"./media/prendas/trajesBaño/tb70.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb34 = new TrajesBano({
    modelo: "Sandi",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb71.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb35 = new TrajesBano({
    modelo: "Nat",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb72.png",
    imagen2:"./media/prendas/trajesBaño/tb73.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb36 = new TrajesBano({
    modelo: "Nat Rose",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb74.png",
    imagen2:"./media/prendas/trajesBaño/tb75.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb37 = new TrajesBano({
    modelo: "Nat Red",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb76.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb38 = new TrajesBano({
    modelo: "Alex",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb78.png",
    imagen2:"./media/prendas/trajesBaño/tb79.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb39 = new TrajesBano({
    modelo: "Nerea",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb81.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb40 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb82.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb41 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb84.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb42 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb85.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb43 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb86.png",
    imagen2:"./media/prendas/trajesBaño/tb87.png",
    imagen3:"./media/prendas/trajesBaño/tb88.png",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb44 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb89.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb45 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb90.png",
    imagen2:"./media/prendas/trajesBaño/tb91.png",
    imagen3:"./media/prendas/trajesBaño/tb92.png",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb46 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb93.jpg",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb47 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb94.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb48 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb95.png",
    imagen2:"./media/prendas/trajesBaño/tb96.png",
    imagen3:"./media/prendas/trajesBaño/tb97.png",
    imagen4:"./media/prendas/trajesBaño/tb98.png",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb49 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb99.png",
    imagen2:"./media/prendas/trajesBaño/tb100.png",
    imagen3:"./media/prendas/trajesBaño/tb101.png",
    imagen4:"./media/prendas/trajesBaño/tb102.png",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb50 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb103.png",
    imagen2:"",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb51 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb104.png",
    imagen2:"./media/prendas/trajesBaño/tb105.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb52 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb106.png",
    imagen2:"./media/prendas/trajesBaño/tb107.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb53 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb109.png",
    imagen2:"./media/prendas/trajesBaño/tb110.png",
    imagen3:"./media/prendas/trajesBaño/tb111.png",
    imagen4:"./media/prendas/trajesBaño/tb112.png",
    imagen5:"./media/prendas/trajesBaño/tb113.png",
    esDanza:"",
    estbria:"",
})
const tb54 = new TrajesBano({
    modelo: "Violeta",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb114.png",
    imagen2:"./media/prendas/trajesBaño/tb115.png",
    imagen3:"./media/prendas/trajesBaño/tb116.png",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb55 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb117.png",
    imagen2:"./media/prendas/trajesBaño/tb118.png",
    imagen3:"./media/prendas/trajesBaño/tb121.png",
    imagen4:"./media/prendas/trajesBaño/tb120.png",
    imagen5:"./media/prendas/trajesBaño/tb122.png",
    esDanza:"",
    estbria:"",
})
const tb56 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb123.png",
    imagen2:"./media/prendas/trajesBaño/tb124.png",
    imagen3:"./media/prendas/trajesBaño/tb125.png",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb57 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb126.png",
    imagen2:"./media/prendas/trajesBaño/tb127.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})
const tb58 = new TrajesBano({
    modelo: "Audrey",
    talla:"L | M | S",
    tela:"Lycra",
    color:"Rosa",
    descripcion:"Este body está diseñado con un aspecto conservador, pero funcional para resaltar la figura del cuerpo mientras haces tu entrenamiento o montaje. Apto para los largos tiempos de ensayo. Sin mangas",
    imagen:"./media/prendas/trajesBaño/tb128.png",
    imagen2:"./media/prendas/trajesBaño/tb129.png",
    imagen3:"",
    imagen4:"",
    imagen5:"",
    esDanza:"",
    estbria:"",
})

var productos = [
    tb1,
    tb2,
    tb3,
    tb4,
    tb5,
    tb6,
    tb7,
    tb8,
    tb9,
    tb10,
    tb11,
    tb12,
    tb13,
    tb14,
    tb15,
    tb16,
    tb17,
    tb18,
    tb19,
    tb20,
    tb21,
    tb22,
    tb23,
    tb24,
    tb25,
    tb26,
    tb27,
    tb28,
    tb29,
    tb30,
    tb31,
    tb32,
    tb33,
    tb34,
    tb35,
    tb36,
    tb37,
    tb38,
    tb39,
    tb40,
    tb41,
    tb42,
    tb43,
    tb44,
    tb45,
    tb46,
    tb47,
    tb48,
    tb49,
    tb50,
    tb51,
    tb52,
    tb53,
    tb54,
    tb55,
    tb56,
    tb57,
    tb58,
    /*tb59,
    tb60,
    tb61,
    tb62,
    tb63,
    tb64,
    tb65,
    tb66,
    tb67,
    tb68,
    tb69,
    tb70,
    tb71,
    tb72,
    tb73,
    tb74,
    tb75,
    tb76,
    tb77,
    tb78,
    tb79,
    tb80,
    tb81,
    tb82,
    tb83,
    tb84,
    tb85,
    tb86,
    tb87,
    tb88,
    tb89,
    tb90,
    tb91,
    tb92,
    tb93,
    tb94,
    tb95,
    tb96,
    tb97,
    tb98,
    tb99,
    tb100,
    tb101,
    tb102,
    tb103,
    tb104,
    tb105,
    tb106,
    tb107,
    tb108,
    tb109,*/
]

productos.forEach(function(producto) {
    var productoElement = document.createElement("div");
    productoElement.innerHTML = `
      <h4>${producto.modelo}</h4>
      <div class="caja">
        <div class="galeria">
          ${producto.imagen ? `<img src="${producto.imagen}" alt="">` : ''}
          ${producto.imagen2 ? `<img src="${producto.imagen2}" alt="">` : ''}
          ${producto.imagen3 ? `<img src="${producto.imagen3}" alt="">` : ''}
          ${producto.imagen4 ? `<img src="${producto.imagen4}" alt="">` : ''}
        </div>
      </div>
      <div class="contenedorVistaPrevia">
        ${producto.imagen ? `<img src="${producto.imagen}" alt="">` : ''}
        ${producto.imagen2 ? `<img src="${producto.imagen2}" alt="">` : ''}
        ${producto.imagen3 ? `<img src="${producto.imagen3}" alt="">` : ''}
        ${producto.imagen4 ? `<img src="${producto.imagen4}" alt="">` : ''}
      </div>
      <div class="parrafos">
        <p>Tallas disponibles: ${producto.talla}</p>
        <p>Tela: ${producto.tela}</p>
        <p>${producto.descripcion}</p>
      </div>`;
  
    // Calcula el ancho del contenedor .galeria en función de la cantidad de imágenes
    var numImagenes = 0;
    if (producto.imagen) numImagenes++;
    if (producto.imagen2) numImagenes++;
    if (producto.imagen3) numImagenes++;
    if (producto.imagen4) numImagenes++;
  
    // Aplica el ancho calculado al contenedor .galeria
    var galeriaElement = productoElement.querySelector(".galeria");
    galeriaElement.style.width = numImagenes * 100 + "%";
  
    prodcatatb.appendChild(productoElement);
  });